repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: sort-simple-yaml

- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v0.17.1
  hooks:
    - id: stylua-github # or stylua-system / stylua-github
      # args: ['--config-path=stylua.toml', '--glob', '**/*.lua -- .']
      args: ['--config-path=stylua.toml']
      types:
        - lua

- repo: local
  hooks:
    - id: fish_syntax
      name: Check fish syntax
      entry: fish --no-execute
      types: [fish]
      language: system
    - id: fish_indent
      name: Indent fish
      entry: fish_indent --write
      types: [fish]
      language: system
