repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: sort-simple-yaml

- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v0.17.1
  hooks:
    - id: stylua-github # or stylua-system / stylua-github
      # args: ['--config-path=stylua.toml', '--glob', '**/*.lua -- .']
      args: ['--config-path=stylua.toml']
      types:
        - lua

- repo: https://github.com/hugoh/pre-commit-fish.git
  rev: v1.2
  hooks:
    - id: fish_syntax
    - id: fish_indent
