#!/usr/bin/env bash

user_dirs=(
    alacritty
    bin
    # emacs
    fish
    git
    karabiner
    ruby
    tmux
    nvim
)

stowit() {
    usr=$1
    app=$2

    # --no-folding: Prevents symlinking directories so it only symlinks files
    #               One known caveat is that I need to run ./syncdots again whenever I add newfiles
    # -v: verbose
    # -R: restow
    # -t: target
    stow --no-folding -v -R -t ${usr} ${app}
}

echo "Stowing apps for user: ${whoami}"

for app in ${user_dirs[@]}; do
    stowit "${HOME}" $app
done

echo ""
echo "Done"
