#!/usr/bin/env bash

user_dirs=(
    alacritty
    bob
    kitty
    bin
    fish
    git
    karabiner
    ruby
    tmux
    nvim
    minivim
)

stowit() {
    usr=$1
    app=$2

    # --no-folding: Prevents symlinking directories so it only symlinks files
    #               One known caveat is that I need to run ./syncdots again whenever I add newfiles
    # -v: verbose
    # -R: restow
    # -t: target
    stow --no-folding -v -R -t ${usr} ${app}
}

unstowit() {
  # TODO
  echo "TODO..."
}

echo "Stowing apps for user: ${whoami}"

if [ -z "$1" ]; then
  for app in ${user_dirs[@]}; do
      stowit "${HOME}" $app
  done
else
  stowit "${HOME}" $1
fi

echo "\nDone"
