#!/usr/bin/env bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"
FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

config=(
  height=35
  blur_radius=30
  position=top
  sticky=off
  padding_left=10
  padding_right=10
  color=$BAR_COLOR
)

sketchybar --bar "${config[@]}"

##### Changing Defaults #####
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  icon.font="SF Pro:Semibold:15.0"
  icon.color="$ICON_COLOR"
  label.font="SF Pro:Semibold:15.0"
  label.color="$LABEL_COLOR"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  background.color=$BAR_COLOR
  background.corner_radius=5
  background.height=24
  padding_left=5
  padding_right=5
)
sketchybar --default "${default[@]}"

# -- Left Items --
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# -- Right Side of Notch items --
source "$ITEM_DIR/media.sh"

# -- Right Items --
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --hotload true
sketchybar --update


# References: https://github.com/linkarzu/dotfiles-latest/blob/main/sketchybar/felixkratz/sketchybarrc
